//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ControlesWindows.ServicioObligatorio {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicioObligatorioSoap", Namespace="http://tempuri.org/")]
    public partial class ServicioObligatorio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AltaCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaCiudadOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaCiudadOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarCiudadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarCiudadOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogueoUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarEmpresasXCiudadYCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback NuevaVisitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListadoVisitasXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback ParaPoderSerializarOperationCompleted;
        
        private System.Threading.SendOrPostCallback ParaPoderSerializarAdminOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioObligatorio() {
            this.Url = global::ControlesWindows.Properties.Settings.Default.ControlesWindows_ServicioObligatorio_ServicioObligatorio;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AltaCategoriaCompletedEventHandler AltaCategoriaCompleted;
        
        /// <remarks/>
        public event BajaCategoriaCompletedEventHandler BajaCategoriaCompleted;
        
        /// <remarks/>
        public event ModificarCategoriaCompletedEventHandler ModificarCategoriaCompleted;
        
        /// <remarks/>
        public event BuscarCategoriaCompletedEventHandler BuscarCategoriaCompleted;
        
        /// <remarks/>
        public event ListarCategoriaCompletedEventHandler ListarCategoriaCompleted;
        
        /// <remarks/>
        public event AltaCiudadCompletedEventHandler AltaCiudadCompleted;
        
        /// <remarks/>
        public event BajaCiudadCompletedEventHandler BajaCiudadCompleted;
        
        /// <remarks/>
        public event BuscarCiudadCompletedEventHandler BuscarCiudadCompleted;
        
        /// <remarks/>
        public event ListarCiudadCompletedEventHandler ListarCiudadCompleted;
        
        /// <remarks/>
        public event LogueoUsuarioCompletedEventHandler LogueoUsuarioCompleted;
        
        /// <remarks/>
        public event AltaUsuarioCompletedEventHandler AltaUsuarioCompleted;
        
        /// <remarks/>
        public event BajaUsuarioCompletedEventHandler BajaUsuarioCompleted;
        
        /// <remarks/>
        public event ModificarUsuarioCompletedEventHandler ModificarUsuarioCompleted;
        
        /// <remarks/>
        public event BuscarUsuarioCompletedEventHandler BuscarUsuarioCompleted;
        
        /// <remarks/>
        public event AltaEmpresaCompletedEventHandler AltaEmpresaCompleted;
        
        /// <remarks/>
        public event BajaEmpresaCompletedEventHandler BajaEmpresaCompleted;
        
        /// <remarks/>
        public event ModificarEmpresaCompletedEventHandler ModificarEmpresaCompleted;
        
        /// <remarks/>
        public event BuscarEmpresaCompletedEventHandler BuscarEmpresaCompleted;
        
        /// <remarks/>
        public event ListarEmpresaCompletedEventHandler ListarEmpresaCompleted;
        
        /// <remarks/>
        public event ListarEmpresasXCiudadYCategoriaCompletedEventHandler ListarEmpresasXCiudadYCategoriaCompleted;
        
        /// <remarks/>
        public event NuevaVisitaCompletedEventHandler NuevaVisitaCompleted;
        
        /// <remarks/>
        public event ListadoVisitasXmlCompletedEventHandler ListadoVisitasXmlCompleted;
        
        /// <remarks/>
        public event ParaPoderSerializarCompletedEventHandler ParaPoderSerializarCompleted;
        
        /// <remarks/>
        public event ParaPoderSerializarAdminCompletedEventHandler ParaPoderSerializarAdminCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaCategoria(Categoria pCategoria) {
            this.Invoke("AltaCategoria", new object[] {
                        pCategoria});
        }
        
        /// <remarks/>
        public void AltaCategoriaAsync(Categoria pCategoria) {
            this.AltaCategoriaAsync(pCategoria, null);
        }
        
        /// <remarks/>
        public void AltaCategoriaAsync(Categoria pCategoria, object userState) {
            if ((this.AltaCategoriaOperationCompleted == null)) {
                this.AltaCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaCategoriaOperationCompleted);
            }
            this.InvokeAsync("AltaCategoria", new object[] {
                        pCategoria}, this.AltaCategoriaOperationCompleted, userState);
        }
        
        private void OnAltaCategoriaOperationCompleted(object arg) {
            if ((this.AltaCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaCategoriaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaCategoria(Categoria pCategoria) {
            this.Invoke("BajaCategoria", new object[] {
                        pCategoria});
        }
        
        /// <remarks/>
        public void BajaCategoriaAsync(Categoria pCategoria) {
            this.BajaCategoriaAsync(pCategoria, null);
        }
        
        /// <remarks/>
        public void BajaCategoriaAsync(Categoria pCategoria, object userState) {
            if ((this.BajaCategoriaOperationCompleted == null)) {
                this.BajaCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaCategoriaOperationCompleted);
            }
            this.InvokeAsync("BajaCategoria", new object[] {
                        pCategoria}, this.BajaCategoriaOperationCompleted, userState);
        }
        
        private void OnBajaCategoriaOperationCompleted(object arg) {
            if ((this.BajaCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaCategoriaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarCategoria(Categoria pCategoria) {
            this.Invoke("ModificarCategoria", new object[] {
                        pCategoria});
        }
        
        /// <remarks/>
        public void ModificarCategoriaAsync(Categoria pCategoria) {
            this.ModificarCategoriaAsync(pCategoria, null);
        }
        
        /// <remarks/>
        public void ModificarCategoriaAsync(Categoria pCategoria, object userState) {
            if ((this.ModificarCategoriaOperationCompleted == null)) {
                this.ModificarCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarCategoriaOperationCompleted);
            }
            this.InvokeAsync("ModificarCategoria", new object[] {
                        pCategoria}, this.ModificarCategoriaOperationCompleted, userState);
        }
        
        private void OnModificarCategoriaOperationCompleted(object arg) {
            if ((this.ModificarCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarCategoriaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Categoria BuscarCategoria(string pId) {
            object[] results = this.Invoke("BuscarCategoria", new object[] {
                        pId});
            return ((Categoria)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarCategoriaAsync(string pId) {
            this.BuscarCategoriaAsync(pId, null);
        }
        
        /// <remarks/>
        public void BuscarCategoriaAsync(string pId, object userState) {
            if ((this.BuscarCategoriaOperationCompleted == null)) {
                this.BuscarCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarCategoriaOperationCompleted);
            }
            this.InvokeAsync("BuscarCategoria", new object[] {
                        pId}, this.BuscarCategoriaOperationCompleted, userState);
        }
        
        private void OnBuscarCategoriaOperationCompleted(object arg) {
            if ((this.BuscarCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarCategoriaCompleted(this, new BuscarCategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Categoria[] ListarCategoria() {
            object[] results = this.Invoke("ListarCategoria", new object[0]);
            return ((Categoria[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarCategoriaAsync() {
            this.ListarCategoriaAsync(null);
        }
        
        /// <remarks/>
        public void ListarCategoriaAsync(object userState) {
            if ((this.ListarCategoriaOperationCompleted == null)) {
                this.ListarCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarCategoriaOperationCompleted);
            }
            this.InvokeAsync("ListarCategoria", new object[0], this.ListarCategoriaOperationCompleted, userState);
        }
        
        private void OnListarCategoriaOperationCompleted(object arg) {
            if ((this.ListarCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCategoriaCompleted(this, new ListarCategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaCiudad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaCiudad(Ciudad pCiudad) {
            this.Invoke("AltaCiudad", new object[] {
                        pCiudad});
        }
        
        /// <remarks/>
        public void AltaCiudadAsync(Ciudad pCiudad) {
            this.AltaCiudadAsync(pCiudad, null);
        }
        
        /// <remarks/>
        public void AltaCiudadAsync(Ciudad pCiudad, object userState) {
            if ((this.AltaCiudadOperationCompleted == null)) {
                this.AltaCiudadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaCiudadOperationCompleted);
            }
            this.InvokeAsync("AltaCiudad", new object[] {
                        pCiudad}, this.AltaCiudadOperationCompleted, userState);
        }
        
        private void OnAltaCiudadOperationCompleted(object arg) {
            if ((this.AltaCiudadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaCiudadCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaCiudad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaCiudad(Ciudad pCiudad) {
            this.Invoke("BajaCiudad", new object[] {
                        pCiudad});
        }
        
        /// <remarks/>
        public void BajaCiudadAsync(Ciudad pCiudad) {
            this.BajaCiudadAsync(pCiudad, null);
        }
        
        /// <remarks/>
        public void BajaCiudadAsync(Ciudad pCiudad, object userState) {
            if ((this.BajaCiudadOperationCompleted == null)) {
                this.BajaCiudadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaCiudadOperationCompleted);
            }
            this.InvokeAsync("BajaCiudad", new object[] {
                        pCiudad}, this.BajaCiudadOperationCompleted, userState);
        }
        
        private void OnBajaCiudadOperationCompleted(object arg) {
            if ((this.BajaCiudadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaCiudadCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarCiudad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Ciudad BuscarCiudad(string pCodDepto, string pNombre) {
            object[] results = this.Invoke("BuscarCiudad", new object[] {
                        pCodDepto,
                        pNombre});
            return ((Ciudad)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarCiudadAsync(string pCodDepto, string pNombre) {
            this.BuscarCiudadAsync(pCodDepto, pNombre, null);
        }
        
        /// <remarks/>
        public void BuscarCiudadAsync(string pCodDepto, string pNombre, object userState) {
            if ((this.BuscarCiudadOperationCompleted == null)) {
                this.BuscarCiudadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarCiudadOperationCompleted);
            }
            this.InvokeAsync("BuscarCiudad", new object[] {
                        pCodDepto,
                        pNombre}, this.BuscarCiudadOperationCompleted, userState);
        }
        
        private void OnBuscarCiudadOperationCompleted(object arg) {
            if ((this.BuscarCiudadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarCiudadCompleted(this, new BuscarCiudadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarCiudad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Ciudad[] ListarCiudad(string pDepartamento) {
            object[] results = this.Invoke("ListarCiudad", new object[] {
                        pDepartamento});
            return ((Ciudad[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarCiudadAsync(string pDepartamento) {
            this.ListarCiudadAsync(pDepartamento, null);
        }
        
        /// <remarks/>
        public void ListarCiudadAsync(string pDepartamento, object userState) {
            if ((this.ListarCiudadOperationCompleted == null)) {
                this.ListarCiudadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarCiudadOperationCompleted);
            }
            this.InvokeAsync("ListarCiudad", new object[] {
                        pDepartamento}, this.ListarCiudadOperationCompleted, userState);
        }
        
        private void OnListarCiudadOperationCompleted(object arg) {
            if ((this.ListarCiudadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarCiudadCompleted(this, new ListarCiudadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LogueoUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario LogueoUsuario(string pNombreUsuario, string pContrasenia) {
            object[] results = this.Invoke("LogueoUsuario", new object[] {
                        pNombreUsuario,
                        pContrasenia});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void LogueoUsuarioAsync(string pNombreUsuario, string pContrasenia) {
            this.LogueoUsuarioAsync(pNombreUsuario, pContrasenia, null);
        }
        
        /// <remarks/>
        public void LogueoUsuarioAsync(string pNombreUsuario, string pContrasenia, object userState) {
            if ((this.LogueoUsuarioOperationCompleted == null)) {
                this.LogueoUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogueoUsuarioOperationCompleted);
            }
            this.InvokeAsync("LogueoUsuario", new object[] {
                        pNombreUsuario,
                        pContrasenia}, this.LogueoUsuarioOperationCompleted, userState);
        }
        
        private void OnLogueoUsuarioOperationCompleted(object arg) {
            if ((this.LogueoUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogueoUsuarioCompleted(this, new LogueoUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaUsuario(Usuario pUsuario) {
            this.Invoke("AltaUsuario", new object[] {
                        pUsuario});
        }
        
        /// <remarks/>
        public void AltaUsuarioAsync(Usuario pUsuario) {
            this.AltaUsuarioAsync(pUsuario, null);
        }
        
        /// <remarks/>
        public void AltaUsuarioAsync(Usuario pUsuario, object userState) {
            if ((this.AltaUsuarioOperationCompleted == null)) {
                this.AltaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaUsuarioOperationCompleted);
            }
            this.InvokeAsync("AltaUsuario", new object[] {
                        pUsuario}, this.AltaUsuarioOperationCompleted, userState);
        }
        
        private void OnAltaUsuarioOperationCompleted(object arg) {
            if ((this.AltaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaUsuario(Usuario pUsuario) {
            this.Invoke("BajaUsuario", new object[] {
                        pUsuario});
        }
        
        /// <remarks/>
        public void BajaUsuarioAsync(Usuario pUsuario) {
            this.BajaUsuarioAsync(pUsuario, null);
        }
        
        /// <remarks/>
        public void BajaUsuarioAsync(Usuario pUsuario, object userState) {
            if ((this.BajaUsuarioOperationCompleted == null)) {
                this.BajaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaUsuarioOperationCompleted);
            }
            this.InvokeAsync("BajaUsuario", new object[] {
                        pUsuario}, this.BajaUsuarioOperationCompleted, userState);
        }
        
        private void OnBajaUsuarioOperationCompleted(object arg) {
            if ((this.BajaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarUsuario(Usuario pUsuario) {
            this.Invoke("ModificarUsuario", new object[] {
                        pUsuario});
        }
        
        /// <remarks/>
        public void ModificarUsuarioAsync(Usuario pUsuario) {
            this.ModificarUsuarioAsync(pUsuario, null);
        }
        
        /// <remarks/>
        public void ModificarUsuarioAsync(Usuario pUsuario, object userState) {
            if ((this.ModificarUsuarioOperationCompleted == null)) {
                this.ModificarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarUsuarioOperationCompleted);
            }
            this.InvokeAsync("ModificarUsuario", new object[] {
                        pUsuario}, this.ModificarUsuarioOperationCompleted, userState);
        }
        
        private void OnModificarUsuarioOperationCompleted(object arg) {
            if ((this.ModificarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario BuscarUsuario(int pCi) {
            object[] results = this.Invoke("BuscarUsuario", new object[] {
                        pCi});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarUsuarioAsync(int pCi) {
            this.BuscarUsuarioAsync(pCi, null);
        }
        
        /// <remarks/>
        public void BuscarUsuarioAsync(int pCi, object userState) {
            if ((this.BuscarUsuarioOperationCompleted == null)) {
                this.BuscarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarUsuarioOperationCompleted);
            }
            this.InvokeAsync("BuscarUsuario", new object[] {
                        pCi}, this.BuscarUsuarioOperationCompleted, userState);
        }
        
        private void OnBuscarUsuarioOperationCompleted(object arg) {
            if ((this.BuscarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarUsuarioCompleted(this, new BuscarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaEmpresa(Empresa pEmpresa) {
            this.Invoke("AltaEmpresa", new object[] {
                        pEmpresa});
        }
        
        /// <remarks/>
        public void AltaEmpresaAsync(Empresa pEmpresa) {
            this.AltaEmpresaAsync(pEmpresa, null);
        }
        
        /// <remarks/>
        public void AltaEmpresaAsync(Empresa pEmpresa, object userState) {
            if ((this.AltaEmpresaOperationCompleted == null)) {
                this.AltaEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaEmpresaOperationCompleted);
            }
            this.InvokeAsync("AltaEmpresa", new object[] {
                        pEmpresa}, this.AltaEmpresaOperationCompleted, userState);
        }
        
        private void OnAltaEmpresaOperationCompleted(object arg) {
            if ((this.AltaEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaEmpresaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaEmpresa(Empresa pEmpresa) {
            this.Invoke("BajaEmpresa", new object[] {
                        pEmpresa});
        }
        
        /// <remarks/>
        public void BajaEmpresaAsync(Empresa pEmpresa) {
            this.BajaEmpresaAsync(pEmpresa, null);
        }
        
        /// <remarks/>
        public void BajaEmpresaAsync(Empresa pEmpresa, object userState) {
            if ((this.BajaEmpresaOperationCompleted == null)) {
                this.BajaEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaEmpresaOperationCompleted);
            }
            this.InvokeAsync("BajaEmpresa", new object[] {
                        pEmpresa}, this.BajaEmpresaOperationCompleted, userState);
        }
        
        private void OnBajaEmpresaOperationCompleted(object arg) {
            if ((this.BajaEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaEmpresaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarEmpresa(Empresa pEmpresa) {
            this.Invoke("ModificarEmpresa", new object[] {
                        pEmpresa});
        }
        
        /// <remarks/>
        public void ModificarEmpresaAsync(Empresa pEmpresa) {
            this.ModificarEmpresaAsync(pEmpresa, null);
        }
        
        /// <remarks/>
        public void ModificarEmpresaAsync(Empresa pEmpresa, object userState) {
            if ((this.ModificarEmpresaOperationCompleted == null)) {
                this.ModificarEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarEmpresaOperationCompleted);
            }
            this.InvokeAsync("ModificarEmpresa", new object[] {
                        pEmpresa}, this.ModificarEmpresaOperationCompleted, userState);
        }
        
        private void OnModificarEmpresaOperationCompleted(object arg) {
            if ((this.ModificarEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarEmpresaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Empresa BuscarEmpresa(string pRut) {
            object[] results = this.Invoke("BuscarEmpresa", new object[] {
                        pRut});
            return ((Empresa)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarEmpresaAsync(string pRut) {
            this.BuscarEmpresaAsync(pRut, null);
        }
        
        /// <remarks/>
        public void BuscarEmpresaAsync(string pRut, object userState) {
            if ((this.BuscarEmpresaOperationCompleted == null)) {
                this.BuscarEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarEmpresaOperationCompleted);
            }
            this.InvokeAsync("BuscarEmpresa", new object[] {
                        pRut}, this.BuscarEmpresaOperationCompleted, userState);
        }
        
        private void OnBuscarEmpresaOperationCompleted(object arg) {
            if ((this.BuscarEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarEmpresaCompleted(this, new BuscarEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Empresa[] ListarEmpresa() {
            object[] results = this.Invoke("ListarEmpresa", new object[0]);
            return ((Empresa[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarEmpresaAsync() {
            this.ListarEmpresaAsync(null);
        }
        
        /// <remarks/>
        public void ListarEmpresaAsync(object userState) {
            if ((this.ListarEmpresaOperationCompleted == null)) {
                this.ListarEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarEmpresaOperationCompleted);
            }
            this.InvokeAsync("ListarEmpresa", new object[0], this.ListarEmpresaOperationCompleted, userState);
        }
        
        private void OnListarEmpresaOperationCompleted(object arg) {
            if ((this.ListarEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarEmpresaCompleted(this, new ListarEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarEmpresasXCiudadYCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Empresa[] ListarEmpresasXCiudadYCategoria(Ciudad pCiudad, Categoria pCategoria) {
            object[] results = this.Invoke("ListarEmpresasXCiudadYCategoria", new object[] {
                        pCiudad,
                        pCategoria});
            return ((Empresa[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarEmpresasXCiudadYCategoriaAsync(Ciudad pCiudad, Categoria pCategoria) {
            this.ListarEmpresasXCiudadYCategoriaAsync(pCiudad, pCategoria, null);
        }
        
        /// <remarks/>
        public void ListarEmpresasXCiudadYCategoriaAsync(Ciudad pCiudad, Categoria pCategoria, object userState) {
            if ((this.ListarEmpresasXCiudadYCategoriaOperationCompleted == null)) {
                this.ListarEmpresasXCiudadYCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarEmpresasXCiudadYCategoriaOperationCompleted);
            }
            this.InvokeAsync("ListarEmpresasXCiudadYCategoria", new object[] {
                        pCiudad,
                        pCategoria}, this.ListarEmpresasXCiudadYCategoriaOperationCompleted, userState);
        }
        
        private void OnListarEmpresasXCiudadYCategoriaOperationCompleted(object arg) {
            if ((this.ListarEmpresasXCiudadYCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarEmpresasXCiudadYCategoriaCompleted(this, new ListarEmpresasXCiudadYCategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NuevaVisita", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void NuevaVisita(Empresa pEmpresa) {
            this.Invoke("NuevaVisita", new object[] {
                        pEmpresa});
        }
        
        /// <remarks/>
        public void NuevaVisitaAsync(Empresa pEmpresa) {
            this.NuevaVisitaAsync(pEmpresa, null);
        }
        
        /// <remarks/>
        public void NuevaVisitaAsync(Empresa pEmpresa, object userState) {
            if ((this.NuevaVisitaOperationCompleted == null)) {
                this.NuevaVisitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNuevaVisitaOperationCompleted);
            }
            this.InvokeAsync("NuevaVisita", new object[] {
                        pEmpresa}, this.NuevaVisitaOperationCompleted, userState);
        }
        
        private void OnNuevaVisitaOperationCompleted(object arg) {
            if ((this.NuevaVisitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NuevaVisitaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListadoVisitasXml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ListadoVisitasXml(Cliente pCliente) {
            object[] results = this.Invoke("ListadoVisitasXml", new object[] {
                        pCliente});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ListadoVisitasXmlAsync(Cliente pCliente) {
            this.ListadoVisitasXmlAsync(pCliente, null);
        }
        
        /// <remarks/>
        public void ListadoVisitasXmlAsync(Cliente pCliente, object userState) {
            if ((this.ListadoVisitasXmlOperationCompleted == null)) {
                this.ListadoVisitasXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListadoVisitasXmlOperationCompleted);
            }
            this.InvokeAsync("ListadoVisitasXml", new object[] {
                        pCliente}, this.ListadoVisitasXmlOperationCompleted, userState);
        }
        
        private void OnListadoVisitasXmlOperationCompleted(object arg) {
            if ((this.ListadoVisitasXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListadoVisitasXmlCompleted(this, new ListadoVisitasXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ParaPoderSerializar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ParaPoderSerializar(Administrador unAdmin, Cliente unCliente) {
            this.Invoke("ParaPoderSerializar", new object[] {
                        unAdmin,
                        unCliente});
        }
        
        /// <remarks/>
        public void ParaPoderSerializarAsync(Administrador unAdmin, Cliente unCliente) {
            this.ParaPoderSerializarAsync(unAdmin, unCliente, null);
        }
        
        /// <remarks/>
        public void ParaPoderSerializarAsync(Administrador unAdmin, Cliente unCliente, object userState) {
            if ((this.ParaPoderSerializarOperationCompleted == null)) {
                this.ParaPoderSerializarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParaPoderSerializarOperationCompleted);
            }
            this.InvokeAsync("ParaPoderSerializar", new object[] {
                        unAdmin,
                        unCliente}, this.ParaPoderSerializarOperationCompleted, userState);
        }
        
        private void OnParaPoderSerializarOperationCompleted(object arg) {
            if ((this.ParaPoderSerializarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParaPoderSerializarCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ParaPoderSerializarAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Administrador ParaPoderSerializarAdmin() {
            object[] results = this.Invoke("ParaPoderSerializarAdmin", new object[0]);
            return ((Administrador)(results[0]));
        }
        
        /// <remarks/>
        public void ParaPoderSerializarAdminAsync() {
            this.ParaPoderSerializarAdminAsync(null);
        }
        
        /// <remarks/>
        public void ParaPoderSerializarAdminAsync(object userState) {
            if ((this.ParaPoderSerializarAdminOperationCompleted == null)) {
                this.ParaPoderSerializarAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParaPoderSerializarAdminOperationCompleted);
            }
            this.InvokeAsync("ParaPoderSerializarAdmin", new object[0], this.ParaPoderSerializarAdminOperationCompleted, userState);
        }
        
        private void OnParaPoderSerializarAdminOperationCompleted(object arg) {
            if ((this.ParaPoderSerializarAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParaPoderSerializarAdminCompleted(this, new ParaPoderSerializarAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Categoria {
        
        private string identificadorField;
        
        private string nombreField;
        
        private string descripcionField;
        
        /// <comentarios/>
        public string Identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Visita {
        
        private Cliente clienteField;
        
        private string nombreClienteField;
        
        private System.DateTime fechaYHoraField;
        
        private bool visitaAceptadaField;
        
        /// <comentarios/>
        public Cliente Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
            }
        }
        
        /// <comentarios/>
        public string NombreCliente {
            get {
                return this.nombreClienteField;
            }
            set {
                this.nombreClienteField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaYHora {
            get {
                return this.fechaYHoraField;
            }
            set {
                this.fechaYHoraField = value;
            }
        }
        
        /// <comentarios/>
        public bool VisitaAceptada {
            get {
                return this.visitaAceptadaField;
            }
            set {
                this.visitaAceptadaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente : Usuario {
        
        private int edadField;
        
        /// <comentarios/>
        public int Edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Administrador))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Usuario {
        
        private int ciField;
        
        private string nombreField;
        
        private string nombreUsuarioField;
        
        private string contraseniaField;
        
        /// <comentarios/>
        public int CI {
            get {
                return this.ciField;
            }
            set {
                this.ciField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string NombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string Contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                this.contraseniaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Administrador : Usuario {
        
        private bool veListadoField;
        
        /// <comentarios/>
        public bool VeListado {
            get {
                return this.veListadoField;
            }
            set {
                this.veListadoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Telefono {
        
        private string numeroField;
        
        /// <comentarios/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Empresa {
        
        private string rutField;
        
        private string nombreField;
        
        private string direccionField;
        
        private Telefono[] telefonosField;
        
        private Ciudad ciudadField;
        
        private Categoria categoriaField;
        
        private Visita[] visitasField;
        
        private int cantidadVisitasField;
        
        private string fechaUltimaVisitaField;
        
        private string nombreUltimaVisitaField;
        
        /// <comentarios/>
        public string Rut {
            get {
                return this.rutField;
            }
            set {
                this.rutField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <comentarios/>
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <comentarios/>
        public Telefono[] Telefonos {
            get {
                return this.telefonosField;
            }
            set {
                this.telefonosField = value;
            }
        }
        
        /// <comentarios/>
        public Ciudad Ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
            }
        }
        
        /// <comentarios/>
        public Categoria Categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
            }
        }
        
        /// <comentarios/>
        public Visita[] Visitas {
            get {
                return this.visitasField;
            }
            set {
                this.visitasField = value;
            }
        }
        
        /// <comentarios/>
        public int CantidadVisitas {
            get {
                return this.cantidadVisitasField;
            }
            set {
                this.cantidadVisitasField = value;
            }
        }
        
        /// <comentarios/>
        public string FechaUltimaVisita {
            get {
                return this.fechaUltimaVisitaField;
            }
            set {
                this.fechaUltimaVisitaField = value;
            }
        }
        
        /// <comentarios/>
        public string NombreUltimaVisita {
            get {
                return this.nombreUltimaVisitaField;
            }
            set {
                this.nombreUltimaVisitaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Ciudad {
        
        private string codDeptoField;
        
        private string nombreField;
        
        /// <comentarios/>
        public string CodDepto {
            get {
                return this.codDeptoField;
            }
            set {
                this.codDeptoField = value;
            }
        }
        
        /// <comentarios/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void AltaCategoriaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void BajaCategoriaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ModificarCategoriaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void BuscarCategoriaCompletedEventHandler(object sender, BuscarCategoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Categoria Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Categoria)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ListarCategoriaCompletedEventHandler(object sender, ListarCategoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Categoria[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Categoria[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void AltaCiudadCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void BajaCiudadCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void BuscarCiudadCompletedEventHandler(object sender, BuscarCiudadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarCiudadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarCiudadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Ciudad Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Ciudad)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ListarCiudadCompletedEventHandler(object sender, ListarCiudadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarCiudadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarCiudadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Ciudad[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Ciudad[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void LogueoUsuarioCompletedEventHandler(object sender, LogueoUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogueoUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogueoUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void AltaUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void BajaUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ModificarUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void BuscarUsuarioCompletedEventHandler(object sender, BuscarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void AltaEmpresaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void BajaEmpresaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ModificarEmpresaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void BuscarEmpresaCompletedEventHandler(object sender, BuscarEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empresa Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empresa)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ListarEmpresaCompletedEventHandler(object sender, ListarEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empresa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empresa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ListarEmpresasXCiudadYCategoriaCompletedEventHandler(object sender, ListarEmpresasXCiudadYCategoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarEmpresasXCiudadYCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarEmpresasXCiudadYCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Empresa[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Empresa[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void NuevaVisitaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ListadoVisitasXmlCompletedEventHandler(object sender, ListadoVisitasXmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListadoVisitasXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListadoVisitasXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ParaPoderSerializarCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void ParaPoderSerializarAdminCompletedEventHandler(object sender, ParaPoderSerializarAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParaPoderSerializarAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ParaPoderSerializarAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Administrador Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Administrador)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591